name: publish-beta

on:
  release:
    types: [prereleased]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
      fail-fast: true

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        registry-url: https://registry.npmjs.org/

    - name: checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test

    - name: Publish BETA build
      run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN_SECRET}}
  